### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by NevenaKlo**
The file 'hu.yaml' has been added. This is the Hungarian translation of the 'en-us_for_translation.yaml' file.

### CODE REVIEW

**Comment by becky-gilbert** [comment]
Thanks very much for this contribution @NevenaKlo! 

I'll have a look at it as soon as possible, and if all looks good, merge it into our develop (staging) branch. At some point after that we can move it into production. I'll keep you posted on this, in case you're able to help us test it on the staging and/or production servers.

**Comment by NevenaKlo** [comment]
Hi @becky-gilbert! I have just added the Basque translation as well. If you need someone to test these out, I'd be happy to.

**Comment by becky-gilbert** [comment]
Hi @NevenaKlo, I'm fixing a few syntax errors in the YAML files and I ran across something that looks like a translation error. In the Hungarian file, I'm seeing this for the GARDEN consent template:
```yaml
consent-garden:
    header: "Hozzájárulás a kísérletben  való részvételhez: {experiment} a GARDEN projekthez" {name} által vezetett kutatók {institution} vezetik ezt a tanulmányt, {kísérlet}, a Lookit-on.: {experiment} for Project GARDEN"
    intro-sentence: '{institution} intézetben található kutatók a {name} vezetésével folyik ez a kutatás on Lookit-on.'
```
And this is the English version:
```yaml
consent-garden:
    header: "Consent to participate in research: {experiment} for Project GARDEN"
    intro-sentence: Researchers led by {name} at {institution} are running this study, {experiment}, on Lookit.
```
In the Hungarian file, I noticed that: 
1. the text for the `header` line contains more variables than it should (`{institution}`, `{name}`) and an incorrect variable name (`{kísérlet}`)
2. the text for the `intro-sentence` line is missing one of the variables (`{experiment}`)

Would you mind double-checking those lines and let me know what they should be? Feel free to update the PR or just post the changes here (I'm already making the syntax changes so it's no problem). Thank you!

**Comment by NevenaKlo** [comment]
Hi Becky, apologies for the error! The lines should be as follows:

header: "Hozzájárulás a kísérletben  való részvételhez: {experiment} a
GARDEN projekthez"

intro-sentence:{name} által vezetett kutatók {institution} vezetik ezt
a tanulmányt, {kísérlet}, a Lookit-on.






Il giorno mar 2 apr 2024 alle ore 21:43 Becky Gilbert <
***@***.***> ha scritto:

**Comment by becky-gilbert** [comment]
@NevenaKlo thanks for the quick response! But in this corrected version that you provided:
```
intro-sentence:{name} által vezetett kutatók {institution} vezetik ezt
a tanulmányt, {kísérlet}, a Lookit-on.
```
I assume that `{kísérlet}` should be `{experiment}`, since variable names should not be translated and the experiment variable is still missing from that line. Does that look right to you?

**Comment by NevenaKlo** [comment]
Yes sorry, that’s the Hungarian word for “experiment”!

**Comment by becky-gilbert** [comment]
Ha, sorry, I could've looked that up! 

Thank you!

**Comment by becky-gilbert** [comment]
Hi again @NevenaKlo, I've run into another issue that I have a question about. In the Basque translation file, I'm seeing some missing parameters that need to be included in the translation text. For instance, the "only_adult" parameter is passed into the consent template, and that value is used to conditionally change parts of the text for experiments in which just an adult is participating (parent surveys, etc.). 

Here's a list of the items in the EU file that are missing the "only_adult" parameter:
- "consent-template-5.data-use-researchers-item-3"
- "consent-template-5.data-use-researchers-content-2"
- "consent-template-5.publication-content"
- "consent-template-5.contact-statement-1"
- "consent-template-5.contact-statement-2"

The EU file is also missing the "omit_injury" parameter in this part:
- "consent-template-5.contact-statement-1" 

And it is missing the "data_sharing_learn" parameter in this part:
- "consent-garden.data-sharing-content" 

For the true/false "only_adult" parameter, it's fine if the text is the same for both values of that parameter (e.g. if the translation doesn't need to make the same distinctions in the English version, such as "you" vs "your child"). If that's the case, just let me know and I can insert the parameter in a way that doesn't make any actual changes to the translation (it does have to be in there in order to get rid of the compiling errors). But I would appreciate it if you could just double check to see whether this is actual the case vs whether the conditional translation was missed by accident.

For the true/false "omit_injury" parameter, this should be referenced in your translation file because its value should have an effect on the translation regardless of the language. Similarly, "data_sharing_learn" should be referenced in the translation. 

Thanks very much, and please let me know if you have questions or if I can help with anything.

**Comment by becky-gilbert** [comment]
@NevenaKlo I've been trying to make changes directly to your pull request but for some reason I can't make the permissions work. So instead of doing it that way, I'm going to merge this pull request and then create a separate PR with fixes for syntax issues and other errors. 

All I need now are your updates to the EU translations using the two missing parameters that I mentioned above:

- This part should incorporate the "omit_injury" parameter and conditional text: "consent-template-5.contact-statement-1"
- This part needs to incorporate the "data_sharing_learn" parameter: "consent-garden.data-sharing-content"

Thanks!

**Comment by becky-gilbert** [comment]
Thanks so much @NevenaKlo! I think the easiest thing will be for you to just share the revisions in a comment here and I'll put it in a PR. That way I can also check for syntax and build errors.

**Comment by NevenaKlo** [comment]
data-use-researchers-item-3: Parte hartzen duen {only_adult, select, true {} other {haurra}} profile for the {only_adult, select, true {familia kidea} other {haurra}}

**Comment by NevenaKlo** [comment]
Thanks Becky, below are the translations with the parameters. The first occurrence of 'only-adult' was omitted in 'publication-content', that sentence translates into something like '[...] it is not possible to identify the participant [...]', but the others were included.

data-use-researchers-item-3: Parte hartzen duen {only_adult, select, true {} other {haurra}} profile for the {only_adult, select, true {familia kidea} other {haurra}}

data-use-researchers-content-2: Horrek etorkizunean informazio honetan egiten dituzun aldaketak barne hartzen ditu. Zenbait informazio mota jar ditzakegu batera haurren garapenaren inguruan gehiago ikasteko. Adibidez, {only_adult, select, true {zuk zeuk} other {zure haurrak}} haurrak gure taldeko zenbait ikerketatan parte hartuz gero, ikerketatik ikerketara zer emaitza duen begiradu dezakegu, edo anaia-arrebek antzera erantzuten duten begiratu dezakegu. Haurren erantzunen eta familien informazio demografikoaren harremanak ere azter ditzakegu.

    publication-content: Ikerketa honen emaitzak mintegi edo aldizkari zientfikoetan argitaratu daitezke. Baliteke norbanakoen emaitzak argitaratzea, beti ere pertsona identifikatzea ezinezkoa bada; adibidez, zenbatetan begiratu den edo sakatutako botoien sekuentzia. Jaiotze egunak edo izean-abizenak ez dira sekula argitaratzen. Nahiz eta grabazioak partekatzeko baimena eman, grabazioak eta {only_adult, select, true {zure} other {haurraren}} datu demografioak lot ditzakeen informaziorik ez da inoriz argitaratzen.

contact-statement-1: Ikerketa hau {institution}-eko {name} ikertzaileak egiten du. {only_adult, select, true {Zeuk} other {Zuk zeuk edo zure haurrak}} ikerketaren inguruko galderak edo kezkak izanez gero, {omit_injury, select, true {} other {edo edozerrengatik ikerketak kalteren bat eragiten badu,}} mesedez harremanetan jarri {contact}.

 contact-statement-2:  {only_adult, select, true {Zeuk} other {Zuk zeuk edo zure haurrak}} Lookit plataformaren inguruko galderarik edo kezkarik izanez gero, mesedez Lookiteko langileekin jarri harremaneta lookit@mit.edu  helbidean.

 data-sharing-content: Behin <u>ikerketako informazioa</u> des-identifikaturik dagoenean (ikusi <strong>“Nola bermatzen dugu pribatutasuna babesturik dagoela?”</strong>), GARDEN proiektuko beste unibertsitateetako beste ikertzaile batzuekin partekatuko dugu, eta aurkikuntzak idazteko erabiliko da, ondoren argitaratzeko. Des-identifikatutako ikerketako informazioa beste ikertzaile batzuekin ere parteka liteke, aurkikuntzak egiazta ditzaten eta ikas daitekeen besterik dagoen ikus dezaten. Horri esker, hezitzaileek, familiek eta ikertzaileek aurkikuntzak erabiliko dituzte {data_sharing_learn}. <br><br>GARDEN proiektuko zer ikerketatan parte hartzen duzun zure esku baizik ez dago. Baimen inprimaki honekin {experiment} esperimentuan parte hartzea baizik ez duzu onartzen.

**Comment by becky-gilbert** [comment]
Thanks so much @NevenaKlo! I've put all of these changes into a PR here: #368. Could you please have a quick look, and it all looks good then I'll merge it.

**Pull request merged**
