### PR TITLE
Brazilian Portuguese translations

### PR DESCRIPTION
**Pull request by NevenaKlo**
pt-br_frames is a yaml file with translations of the English file available via the FAQ section: https://lookit.readthedocs.io/projects/frameplayer/en/latest/components/exp-frame-base/doc.html#translation.

The BR.po file is a translation of the demographic and registration pages: this is available via the Many Babies at home website (https://manybabies.org/MB-AtHome/).

### CODE REVIEW

**Comment by becky-gilbert** [comment]
Hi @NevenaKlo, thanks very much for this contribution! And sorry for the delay getting back to you.

As this pull request is in the Ember Frameplayer (experiment runner) repository, we can only accept the changes in the `pt-br_frames.yml` file. We do need this file to have a yaml extension and be named with just the locale code: `pt-br.yaml`. And it looks like we already have a Brazilian Portuguese file for the Ember Frameplayer: https://github.com/lookit/ember-lookit-frameplayer/blob/develop/translations/pt-br.yaml. So what we'd like you to do is compare your file (`pt-br_frames.yml`) against ours (`pt-br.yaml`). If you want to make any additions/changes, please make edits to our existing file and then submit a pull request with those changes. (You can either do this on your fork's `develop` branch, which will update this pull request, or you can create a new branch and new pull request).

The `BR.po` file needs to be submitted as a pull request to the [lookit-api repository](https://github.com/lookit/lookit-api), which is the repository that contains all of the code for the Lookit/CHS website (other than the experiment runner). It looks like we already have a locale file for Brazilian Portuguese there: https://github.com/lookit/lookit-api/blob/develop/locale/pt_BR/LC_MESSAGES/django.po. So I think you'll want to fork the lookit-api repository (if you haven't already) and then compare your file (`BR.po`) against our existing file. And again, if you need to make changes, please submit a pull request with edits to the existing `pt_BR/LC_MESSAGES/django.po` file (rather than adding a new file).

I realize this might be confusing - please let me know if you'd like any more guidance or have questions. You can post here or reach me on the Lookit Slack.

**Comment by NevenaKlo** [comment]
Hi Becky,

You can see on Github the changes I have committed to the file
pt-br.yaml. As for
the .po file, I have checked the one available in the lookit-api repository
and it seems to be the same as the one I have! Everything is already there
, the only difference I can see is a different numbering of the
accounts/models, I hope that this is not an issue.

Best,
Nevena

Il giorno ven 5 gen 2024 alle ore 00:34 Becky Gilbert <
***@***.***> ha scritto:

**Comment by becky-gilbert** [comment]
Hi @NevenaKlo, thanks very much for the update. This is almost ready to merge! I just need you to delete the `BR.po` file from your `develop` branch. But please do save your version of that file somewhere so that we can compare it to the one in the `lookit-api` repository. I'm not sure yet if the line number differences matter, so it would be great to have your version in case ours is out of date.

Thanks also for mentioning the that our existing en-us translation file is missing consent-template-2 and consent-garden. I will fix that!

**Comment by becky-gilbert** [comment]
@NevenaKlo this is perfect, thanks! I'm going to merge this into develop now so that I can test it. Assuming all looks good we'll merge it into the master branch, which will make it available on the site. I'll keep you posted on this!

**Pull request merged**
