### PR TITLE
update available languages in docs, edit lang parameter description

### PR DESCRIPTION
**Pull request by becky-gilbert**
This PR adds makes some minor edits to the documentation about the language parameter, and adds the following languages to the list that are available for translation:
- Basque
- Hungarian
- Japanese
- Portuguese
- Portuguese (Brazil)

### CODE REVIEW

**Comment by becky-gilbert** [comment]
@ianchandlercampbell can you have a quick look at this whenever you have a chance? I added the new languages that are available for translation in EFP, and made some minor edits to the description of the language parameter.

**Comment by ianchandlercampbell** [comment]
@becky-gilbert Just reviewed! Just for readability, I might suggest two lists: "Things that are translated:" and "Things that are not translated:" with bullet points underneath each. I'll leave it up to you on whether that's useful or not, the content updates look good.

**Comment by becky-gilbert** [comment]
@ianchandlercampbell ooh yes thank you, much better.

**Comment by ianchandlercampbell** [comment]
You betcha!

Ian Chandler-Campbell, Ph.D.
Open-Source Community Manager, Children Helping Science
<https://childrenhelpingscience.com/>
Research Associate, Project GARDEN
<https://childrenhelpingscience.com/garden/scientists>
ianchandlercampbell.com
he/him/his

**Pull request merged**
