### PR TITLE
New 'consent_garden' template for `video-consent` frame

### PR DESCRIPTION
**Pull request by becky-gilbert**
Closes https://github.com/lookit/lookit-api/issues/1266

This PR contains the new 'consent_garden' template option for the `exp-lookit-video-consent` frame. This template is ONLY to be used by Project GARDEN researchers/studies. The documentation is written in markdown and included with this PR, and will not be added to the Lookit docs site.

We discussed several options for parameterization and providing editable vs uneditable sections/text, but in the end I've gone for parameterizing as much as possible. The default section headers and contents are all editable. I did it this way because it wasn't that much extra work to add in a few more parameters, and in order to future-proof this template as much as possible for changes to wording that might be needed later. However I am happy to remove parameters - just let me know.

You can see a live version of this template in a production site study called "GARDEN Consent Tests". There are a few frame examples in the JSON protocol that you can run -  just change the frame name in the sequence. And feel free to test changes to parameter values.

**Note for Lookit devs:**
We may want to consider moving some of this work over to the main video-consent frame/templates/docs. In particular:
- In the text segments given in the docs, we should standardize the notation to clarify the distinction between text variables that are provided via frame parameters vs those that Lookit automatically generates from the study details.
- Allow HTML formatting for all researcher-provided text segments (currently we allow it for some, but not all).

### CODE REVIEW

**Comment by becky-gilbert** [comment]
@ianchandlercampbell here's the PR for the new GARDEN consent template. Feel free to leave feedback here or on Slack!

**Review by okaycj — APPROVED** [review]
LGTM!  That's a lot of work.

**Comment by becky-gilbert** [comment]
@mekline @ianchandlercampbell below is a screenshot of the GARDEN consent template. And as I mentioned on Slack, you both have access to the GARDEN Consent Tests study on the production server, where you can run the consent frame and edit the parameters. The docs are here: https://github.com/lookit/ember-lookit-frameplayer/blob/garden-consent/app/components/consent-garden/doc.md

Let me know if you'd like any changes, or if you're happy for me to merge this.

Screenshot 2023-09-26 at 12 21 15 PM

**Comment by becky-gilbert** [comment]
@ianchandlercampbell I've fixed the last two issues we discussed: removing double quotes around the study name, and adding the missing header for the contact us section. So I'm going to merge and release this now, but of course if you or your team finds any other issues then please let us know!

Screenshot 2023-09-26 at 4 19 17 PM

Screenshot 2023-09-26 at 4 19 38 PM

**Pull request merged**
